generate module-info.class and manifest
docker-java/docker-java pull request #1972
Opened 2022-10-04 14:39 UTC by stbischof

using bnd jpms-module-info and osgi support

`bnd` could generate `module-info.class` using simple annotations
this also allows to generate a proper osgi-manifest.

[documentation](https://bnd.bndtools.org/chapters/330-jpms.html)

2022-10-04 15:42 UTC, bsideup requested changes
I am fine with fixing the OSGI exports, but we are not ready to commit to provide any OSGI support (e.g. the `OSGiApacheDockerHttpClientService` class that you created).

Could you please reduce the changeset to just the fixed exports? (are they broken, btw?)

2022-10-04 19:54 UTC, stbischof commented
i removed everything that is not just related on Manifest (exports imports) and module-info.

yes, currently the complete OSGi support is broken

2022-10-05 00:43 UTC, bsideup commented
@stbischof I love the idea of using a property for it and reusing the config in the parent pom! 👍 💯 May I kindly ask you make this change? Thanks in advance!

2022-10-05 07:42 UTC, stbischof commented
@bsideup  is this the way you would  prefer?
i will check all manifest again after your okay

2022-10-07 06:26 UTC, stbischof commented
automatic-module-name(jigsaw) and bundle-symbolic-name(osgi) are the same

2022-10-11 00:16 UTC, eddumelendez approved these changes
LGTM

2022-10-18 15:06 UTC, stbischof commented
@bsideup  is this ready to merge?

2022-11-04 19:06 UTC, stbischof commented
@bsideup is there anything i can do to get this merged?

2022-11-21 17:39 UTC, stbischof commented
@eddumelendez 
is there anything i can do to get this merged?

2022-11-30 15:50 UTC, eddumelendez commented
I tried locally and see a lot of warnings. Didn't have enough time to check it, that's the reason why I didn't merge it. Sorry about it.

2022-11-30 16:09 UTC, stbischof commented
I will have a check on warnings and may remove or give info's about

2024-11-26 21:19 UTC, cowwoc commented
@stbischof @eddumelendez What is the status of this PR?

2024-11-26 22:01 UTC, stbischof commented
If you are open to merge a pr i wiuld update this or tomorrow

2024-11-29 04:23 UTC, cowwoc commented
@stbischof I don't have merge permissions and I see that @bsideup still has an open change request open: https://github.com/docker-java/docker-java/pull/1972#pullrequestreview-1130210516

He would need to resolve that request in order to move forward. Also, are you disabling module-info support at https://github.com/docker-java/docker-java/pull/1972/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R299 ? I hope not, since the entire point of this PR is to enable said support.

2024-11-29 05:28 UTC, stbischof commented
This pr uses the bnd maven plugin to generate all the needed manifest data and module-info.class together with the osgi metadata.

2025-06-27 01:26 UTC, closed without merging